import React,{useCallback,useEffect,useState}from"react";
import{Alert,FlatList,Modal,Pressable,SafeAreaView,ScrollView,Text,TextInput,View}from"react-native";
import{colors as C,money,supabase}from"./config";
import{Button,Empty,Header,s}from"./ui";
import LiveVideo from"./LiveVideo";

export default function HomeScreen({profile,user,flash}){
 const[shows,setShows]=useState([]),[search,setSearch]=useState(""),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const{data,error}=await supabase.from("shows").select("id,title,room_name,status,seller_id,current_product_id,auction_ends_at,profiles!shows_seller_id_fkey(display_name,seller_approved),products!shows_current_product_id_fkey(id,title,starting_bid,price)").eq("status","live").order("created_at",{ascending:false});if(!error)setShows(data||[]);setLoading(false);},[]);
 useEffect(()=>{
  load();
  const timer=setInterval(load,4000);
  const channel=supabase.channel("home-live-shows")
   .on("postgres_changes",{event:"*",schema:"public",table:"shows"},payload=>{
    if(payload.eventType==="DELETE"||payload.new?.status!=="live")setShows(current=>current.filter(show=>show.id!==(payload.old?.id||payload.new?.id)));
    load();
   }).subscribe();
  return()=>{clearInterval(timer);supabase.removeChannel(channel)};
 },[load]);
 const filtered=shows.filter(x=>`${x.title} ${x.profiles?.display_name||""}`.toLowerCase().includes(search.toLowerCase()));
 return <View style={{flex:1}}><FlatList data={filtered} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={{gap:12}} contentContainerStyle={s.page} ListHeaderComponent={<><Header title="E&T LIVE" subtitle="Watch verified sellers live" profile={profile}/><View style={s.search}><Text style={{color:C.muted,fontSize:24}}>⌕</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search live streamers" placeholderTextColor={C.muted} style={s.searchInput}/></View><View style={s.between}><Text style={s.section}>Live sellers</Text><Text style={{color:C.red,fontWeight:"900"}}>● {shows.length} LIVE</Text></View></>} ListEmptyComponent={<Empty title={loading?"Finding live sellers…":"No sellers are live right now"} subtitle="Shows appear here automatically when an approved seller starts broadcasting."/>} renderItem={({item})=><ShowCard show={item} onPress={()=>setSelected(item)}/>} /><Viewer show={selected} user={user} onClose={()=>setSelected(null)} flash={flash}/></View>;
}
function ShowCard({show,onPress}){const seller=show.profiles,product=show.products;return <Pressable onPress={onPress} style={x.card}><View style={x.art}><Text style={{fontSize:58}}>📹</Text><View style={x.live}><Text style={x.liveText}>● LIVE</Text></View></View><View style={{padding:12,gap:6}}><Text style={s.title} numberOfLines={2}>{show.title}</Text><View style={s.row}><Text style={s.muted} numberOfLines={1}>{seller?.display_name||"Seller"}</Text>{seller?.seller_approved&&<Text style={s.badge}>✓</Text>}</View>{product&&<Text style={s.price}>{money(product.starting_bid??product.price)}</Text>}</View></Pressable>}
function Viewer({show,user,onClose,flash}){
 const[liveShow,setLiveShow]=useState(show),[product,setProduct]=useState(show?.products||null),[bids,setBids]=useState([]),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[following,setFollowing]=useState(false),[secondsLeft,setSecondsLeft]=useState(0);
 useEffect(()=>{setLiveShow(show);setProduct(show?.products||null);setBids([])},[show]);
 const refreshShow=useCallback(async()=>{if(!show)return;const{data}=await supabase.from("shows").select("id,title,room_name,status,seller_id,current_product_id,auction_ends_at,profiles!shows_seller_id_fkey(display_name,seller_approved),products!shows_current_product_id_fkey(id,title,starting_bid,price)").eq("id",show.id).maybeSingle();if(!data)return;if(data.status!=="live"){Alert.alert("Show ended","The seller ended this livestream.");onClose();return}setLiveShow(data);setProduct(data.products||null);setBids([])},[show,onClose]);
 const load=useCallback(async()=>{if(!liveShow)return;const bidQuery=supabase.from("bids").select("id,amount,bidder_id,profiles!bids_bidder_id_fkey(display_name)").eq("show_id",liveShow.id).order("amount",{ascending:false}).limit(30);if(product?.id)bidQuery.eq("product_id",product.id);const[{data:b},{data:m},{data:f}]=await Promise.all([product?.id?bidQuery:Promise.resolve({data:[]}),supabase.from("messages").select("id,body,user_id,profiles!messages_user_id_fkey(display_name)").eq("show_id",liveShow.id).order("created_at").limit(100),supabase.from("follows").select("seller_id").eq("follower_id",user.id).eq("seller_id",liveShow.seller_id).maybeSingle()]);setBids(b||[]);setMessages(m||[]);setFollowing(!!f);},[liveShow,product?.id,user.id]);
 useEffect(()=>{if(!show)return;load();const ch=supabase.channel(`room-${show.id}`).on("postgres_changes",{event:"*",schema:"public",table:"bids",filter:`show_id=eq.${show.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"messages",filter:`show_id=eq.${show.id}`},load).on("postgres_changes",{event:"UPDATE",schema:"public",table:"shows",filter:`id=eq.${show.id}`},refreshShow).subscribe();return()=>supabase.removeChannel(ch);},[show,load,refreshShow]);
 useEffect(()=>{if(!product||!liveShow?.auction_ends_at){setSecondsLeft(0);return}const tick=()=>setSecondsLeft(Math.max(0,Math.ceil((new Date(liveShow.auction_ends_at).getTime()-Date.now())/1000)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[product,liveShow?.auction_ends_at]);
 if(!liveShow)return null;const top=bids[0]?.amount??product?.starting_bid??product?.price??0;
 const bid=async()=>{if(!product)return Alert.alert("Waiting for product","The seller has not started the next auction yet.");if(secondsLeft<=0)return Alert.alert("Auction ended","This product auction has closed.");const{data,error}=await supabase.rpc("place_timed_live_bid",{target_show:liveShow.id,target_product:product.id});if(error)Alert.alert("Bid failed",error.message);else flash(`Bid placed at ${money(data?.amount??Number(top)+1)} · 3 seconds added`)};
 const send=async()=>{if(!message.trim())return;const body=message.trim();setMessage("");const{error}=await supabase.from("messages").insert({show_id:show.id,user_id:user.id,body});if(error)Alert.alert("Message failed",error.message)};
 const follow=async()=>{if(following)await supabase.from("follows").delete().eq("follower_id",user.id).eq("seller_id",liveShow.seller_id);else await supabase.from("follows").insert({follower_id:user.id,seller_id:liveShow.seller_id});setFollowing(!following)};
 return <Modal visible animationType="slide" onRequestClose={onClose}><SafeAreaView style={s.safe}><View style={s.modalHeader}><Pressable onPress={onClose}><Text style={s.back}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.title}>● LIVE · {liveShow.profiles?.display_name}</Text><Text style={s.muted}>{liveShow.title}</Text></View><Button small ghost title={following?"Following ✓":"Follow"} onPress={follow}/></View><LiveVideo room={liveShow.room_name} user={user}/><ScrollView contentContainerStyle={[s.page,{paddingBottom:30}]}>{product?<><View style={s.between}><Text style={s.logo}>{product.title}</Text><Text style={{color:secondsLeft<=3?C.red:C.orange,fontSize:42,fontWeight:"900"}}>{secondsLeft}</Text></View><Text style={s.muted}>Every accepted bid adds 3 seconds.</Text><View style={[s.panel,s.between]}><View><Text style={s.muted}>CURRENT BID</Text><Text style={{color:C.orange,fontSize:32,fontWeight:"900"}}>{money(top)}</Text></View><Text style={s.muted}>{bids.length} bids</Text></View><Button disabled={secondsLeft<=0} title={secondsLeft<=0?"Auction closing…":`Bid ${money(Number(top)+1)}`} onPress={bid}/></>:<View style={s.panel}><Text style={s.section}>Seller is choosing the next product</Text><Text style={s.muted}>The livestream stays open. The next auction will appear automatically.</Text></View>}<Text style={s.section}>Live chat</Text>{messages.map(m=><View key={m.id} style={x.chat}><Text style={{color:C.orange,fontWeight:"900"}}>{m.profiles?.display_name||"Viewer"}</Text><Text style={s.text}>{m.body}</Text></View>)}<View style={s.row}><TextInput value={message} onChangeText={setMessage} placeholder="Say something…" placeholderTextColor={C.muted} style={[s.input,{flex:1}]}/><Button small title="Send" onPress={send}/></View></ScrollView></SafeAreaView></Modal>;
}
const x={card:{flex:1,maxWidth:"49%",backgroundColor:C.card,borderRadius:16,overflow:"hidden",marginBottom:12,borderColor:C.line,borderWidth:1},art:{height:170,backgroundColor:C.card2,alignItems:"center",justifyContent:"center"},live:{position:"absolute",top:10,left:10,backgroundColor:C.red,paddingHorizontal:9,paddingVertical:6,borderRadius:8},liveText:{color:"white",fontWeight:"900",fontSize:12},chat:{flexDirection:"row",gap:9,backgroundColor:C.card,borderRadius:12,padding:11}};
