import React from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { colors as C } from "./config";

export function Button({ title, onPress, ghost, danger, disabled, small }) {
  return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, ghost && s.ghost, danger && s.danger, small && s.small, (pressed || disabled) && { opacity: .55 }]}><Text style={s.buttonText}>{title}</Text></Pressable>;
}
export function Field({ label, ...props }) {
  return <View style={{ gap: 7 }}>{label && <Text style={s.label}>{label}</Text>}<TextInput {...props} placeholderTextColor={C.muted} style={s.input} /></View>;
}
export function Header({ title, subtitle, profile }) {
  return <View style={s.header}><View style={{ flex: 1 }}><Text style={s.logo}>{title}</Text>{subtitle && <Text style={s.muted}>{subtitle}</Text>}</View><View style={s.avatar}><Text style={s.avatarText}>{(profile?.display_name || "ET").slice(0,2).toUpperCase()}</Text></View></View>;
}
export function Stat({ label, value }) { return <View style={s.stat}><Text style={s.muted}>{label}</Text><Text style={s.title}>{value}</Text></View>; }
export function Empty({ icon="📡", title, subtitle }) { return <View style={s.empty}><Text style={{ fontSize: 44 }}>{icon}</Text><Text style={s.title}>{title}</Text>{subtitle && <Text style={s.muted}>{subtitle}</Text>}</View>; }
export const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:C.bg},page:{padding:18,paddingBottom:105,gap:16},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:C.bg},text:{color:C.text,fontSize:15},muted:{color:C.muted,fontSize:14},label:{color:C.text,fontWeight:"700"},logo:{color:C.text,fontSize:25,fontWeight:"900"},title:{color:C.text,fontSize:17,fontWeight:"800"},section:{color:C.text,fontSize:21,fontWeight:"900"},orange:{color:C.orange},header:{flexDirection:"row",alignItems:"center",gap:12},avatar:{width:46,height:46,borderRadius:23,backgroundColor:C.orange,alignItems:"center",justifyContent:"center"},avatarText:{color:C.bg,fontWeight:"900"},input:{minHeight:51,backgroundColor:C.card2,borderColor:C.line,borderWidth:1,borderRadius:14,paddingHorizontal:15,color:C.text,fontSize:16},button:{minHeight:50,paddingHorizontal:18,borderRadius:14,backgroundColor:C.orange,alignItems:"center",justifyContent:"center"},buttonText:{color:C.text,fontSize:15,fontWeight:"900"},ghost:{backgroundColor:"transparent",borderColor:C.line,borderWidth:1},danger:{backgroundColor:C.red},small:{minHeight:40,paddingHorizontal:12},panel:{backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:18,padding:17,gap:14},warning:{backgroundColor:"#372018",borderColor:C.orange,borderWidth:1,borderRadius:18,padding:17,gap:12},row:{flexDirection:"row",alignItems:"center",gap:10},between:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},stat:{minHeight:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomColor:C.line,borderBottomWidth:1},empty:{backgroundColor:C.card,borderRadius:18,padding:28,alignItems:"center",gap:9},search:{minHeight:56,flexDirection:"row",alignItems:"center",backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:16,paddingHorizontal:15},searchInput:{flex:1,color:C.text,fontSize:16,paddingHorizontal:10},activity:{flexDirection:"row",alignItems:"center",gap:12,backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:15,padding:14},price:{color:C.orange,fontSize:19,fontWeight:"900"},badge:{color:C.orange,fontSize:12,fontWeight:"900"},nav:{position:"absolute",left:0,right:0,bottom:0,height:78,backgroundColor:"#0C1018",borderTopColor:C.line,borderTopWidth:1,flexDirection:"row",paddingBottom:6},navItem:{flex:1,alignItems:"center",justifyContent:"center",gap:3},navIcon:{color:C.muted,fontSize:24},navText:{color:C.muted,fontSize:12,fontWeight:"700"},toast:{position:"absolute",bottom:88,left:20,right:20,backgroundColor:C.green,padding:14,borderRadius:12},toastText:{color:C.bg,fontWeight:"900",textAlign:"center"},back:{color:C.text,fontSize:40},modalHeader:{minHeight:68,flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:16,backgroundColor:C.bg},
});
